version: "3"
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      # args:
      #   WORKDIR: app
    volumes:
      - ./frontend/vite-project:/app
    ports:
      - "5173:5173"
    depends_on:
      - backend
    tty: true
    command: yarn dev --host
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
      # args: #=== Dockerfileに引数として渡せる
      #   WORKDIR: app
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - "./backend:/app"
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
    depends_on:
      - db
    stdin_open: true
    tty: true
volumes:
  mysql-data:
    driver: local
